### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [vmalets/grid-project#1]
Размеры полей не соответствуют макету
![image](https://user-images.githubusercontent.com/8464662/67386616-f9bb8f00-f59d-11e9-967e-5739f26a5f6a.png)
![image](https://user-images.githubusercontent.com/8464662/67386845-63d43400-f59e-11e9-859d-8083d787fe6f.png)

на различных разрешениях нет соответствия макету
![image](https://user-images.githubusercontent.com/8464662/67386712-25d71000-f59e-11e9-9bb4-f3e87573d588.png)

**Comment by vmalets** [comment]
Поработал над ошибками, надеюсь исправил.
